export const INIT = "INIT";
export const INIT_OK = "INIT_OK";
export const INIT_FAIL = "INIT_FAIL";

export const REFRESH_DEPLOYMENTS = "REFRESH_DEPLOYMENTS";
export const REFRESH_DEPLOYMENTS_OK = "REFRESH_DEPLOYMENTS_OK";
export const REFRESH_DEPLOYMENTS_FAIL = "REFRESH_DEPLOYMENTS_FAIL";

export const ADD_DEPLOYMENT = "ADD_DEPLOYMENT";
export const ADD_DEPLOYMENT_OK = "ADD_DEPLOYMENT_OK";
export const ADD_DEPLOYMENT_FAIL = "ADD_DEPLOYMENT_FAIL";

export const DELETE_DEPLOYMENT = "DELETE_DEPLOYMENT";
export const DELETE_DEPLOYMENT_OK = "DELETE_DEPLOYMENT_OK";
export const DELETE_DEPLOYMENT_FAIL = "DELETE_DEPLOYMENT_FAIL";
